// packages/renderer/src/index.ts

import { Drawing, DrawingObject, CanvasSettings } from '../../../src/types';

export function generateSVGString(drawing: Drawing, settings: CanvasSettings): string {
  const { transparentBackground } = settings;
  const width = 800;
  const height = 600;

  let svgContent = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${width} ${height}" width="${width}" height="${height}">\n`;
  
  if (!transparentBackground) {
    svgContent += `  <rect width="100%" height="100%" fill="#ffffff" />\n`;
  }

  drawing.objects.forEach(obj => {
    switch (obj.type) {
      case 'rectangle':
        svgContent += `  <rect id="${obj.id}" x="${obj.x}" y="${obj.y}" width="${obj.width || 0}" height="${obj.height || 0}" fill="${obj.fill}" stroke="${obj.stroke}" stroke-width="${obj.strokeWidth}" />\n`;
        break;
      case 'circle':
        svgContent += `  <circle id="${obj.id}" cx="${obj.x}" cy="${obj.y}" r="${obj.radius || 0}" fill="${obj.fill}" stroke="${obj.stroke}" stroke-width="${obj.strokeWidth}" />\n`;
        break;
      case 'path':
        svgContent += `  <path id="${obj.id}" d="${obj.points || ''}" fill="none" stroke="${obj.stroke}" stroke-width="${obj.strokeWidth}" stroke-linecap="round" stroke-linejoin="round" />\n`;
        break;
      case 'text':
        // Text requires a baseline adjustment to display properly in raw SVGs
        svgContent += `  <text id="${obj.id}" x="${obj.x}" y="${obj.y}" fill="${obj.stroke}" font-family="monospace" font-size="14" dominant-baseline="alphabetic">${obj.text || ''}</text>\n`;
        break;
      case 'image':
        svgContent += `  <image id="${obj.id}" href="${obj.imageUrl || ''}" x="${obj.x}" y="${obj.y}" width="${obj.width || 0}" height="${obj.height || 0}" />\n`;
        break;
    }
  });

  if (settings.includeMetadata) {
    svgContent += `  <!-- Generated by DrawOS - ${new Date().toISOString()} -->\n`;
  }

  svgContent += `</svg>`;
  return svgContent;
}
